data:
  raw_filepath: './data/bank_data.csv'  
eda:
  output_dir: './images/eda'
  plot_histograms: ['Churn', 'Customer_Age', 'Marital_Status', 'Total_Trans_Ct']
matplotlib:
  small_size: 10
  medium_size: 14
  large_size: 16
feature_engineering:
  categorical_columns: [
    'Gender',
    'Education_Level',
    'Marital_Status',
    'Income_Category',
    'Card_Category'                
]
  encoded_cat_names: None
prepare_data:
  training_features: ['Customer_Age', 'Dependent_count', 'Months_on_book',
             'Total_Relationship_Count', 'Months_Inactive_12_mon',
             'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
             'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
             'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
             'Gender_Churn', 'Education_Level_Churn', 'Marital_Status_Churn', 
             'Income_Category_Churn', 'Card_Category_Churn']
  target: 'Churn'
  test_size: 0.3
  random_state: 42  
testing:
  data_filepath:  './data/bank_data.csv'
